apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - name: order-container
        image: your-registry/order-service:latest
        ports:
        - containerPort: 8080
        env:
        - name: ENV_VAR_NAME
          value: "value"
