apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  namespace: auth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth-container
        imagePullPolicy: Never
        image: auth-service:latest
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: config-vol
            mountPath: /app/config.yaml
            subPath: config.yaml
      volumes:
        - name: config-vol
          configMap:
            name: auth-config
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: auth
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP