docker-build:
	docker build -t auth-service:latest -f auth/deployment/Dockerfile .
	docker build -t shop-service:latest -f shop/deployment/Dockerfile .
	docker build -t product-service:latest -f product/deployment/Dockerfile .
	docker build -t warehouse-service:latest -f warehouse/deployment/Dockerfile .
	docker build -t order-service:latest -f order/deployment/Dockerfile .