apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
  namespace: order
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - name: order-container
        imagePullPolicy: Never
        image: order-service:latest
        ports:
        - containerPort: 8080
        - containerPort: 9090
        volumeMounts:
          - name: config-vol
            mountPath: /app/config.yaml
            subPath: config.yaml
      volumes:
        - name: config-vol
          configMap:
            name: order-config
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: order
spec:
  selector:
    app: order
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
    - protocol: TCP
      port: 9090
      targetPort: 9090
  type: ClusterIP